name: Deploy LINE Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your Flask app
      run: python your_app.py
