name: Deploy LINE Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    # 添加一个步骤，将gunicorn的输出重定向到文件
    - name: Run gunicorn
      run: gunicorn -w 4 -b 0.0.0.0:8080 "LINE_BOT_2023_8_9:app" > gunicorn.log 2>&1

    # 添加一个步骤，显示gunicorn的日志内容
    - name: Show gunicorn log
      run: cat gunicorn.log
