name: Deploy LINE Bot

on:
  push:
    branches:
      - main  # 替换成您的主分支名称，例如：master

jobs:
  deploy:
    runs-on: ubuntu-latest  # 您可以选择不同的操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取存储库代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 指定您的 Python 版本

    - name: Install dependencies
      run: pip install -r requirements.txt  # 如果您有依赖文件，请适当更改此命令

    - name: Run your Flask app
      run: python your_app.py  # 替换成您的 Flask 应用的启动命令
